// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/change_stream.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastLsn       string                 `protobuf:"bytes,1,opt,name=last_lsn,json=lastLsn,proto3" json:"last_lsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_api_change_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_change_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_api_change_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetLastLsn() string {
	if x != nil {
		return x.LastLsn
	}
	return ""
}

type Change struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Lsn   string                 `protobuf:"bytes,1,opt,name=lsn,proto3" json:"lsn,omitempty"`
	Type  string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Change_Dml
	//	*Change_Ddl
	Data          isChange_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_api_change_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_api_change_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_api_change_stream_proto_rawDescGZIP(), []int{1}
}

func (x *Change) GetLsn() string {
	if x != nil {
		return x.Lsn
	}
	return ""
}

func (x *Change) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Change) GetData() isChange_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Change) GetDml() *DMLData {
	if x != nil {
		if x, ok := x.Data.(*Change_Dml); ok {
			return x.Dml
		}
	}
	return nil
}

func (x *Change) GetDdl() *DDLData {
	if x != nil {
		if x, ok := x.Data.(*Change_Ddl); ok {
			return x.Ddl
		}
	}
	return nil
}

type isChange_Data interface {
	isChange_Data()
}

type Change_Dml struct {
	Dml *DMLData `protobuf:"bytes,3,opt,name=dml,proto3,oneof"`
}

type Change_Ddl struct {
	Ddl *DDLData `protobuf:"bytes,4,opt,name=ddl,proto3,oneof"`
}

func (*Change_Dml) isChange_Data() {}

func (*Change_Ddl) isChange_Data() {}

type DMLData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	ColumnNames   []string               `protobuf:"bytes,2,rep,name=column_names,json=columnNames,proto3" json:"column_names,omitempty"`
	ColumnValues  []string               `protobuf:"bytes,3,rep,name=column_values,json=columnValues,proto3" json:"column_values,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	OldKeys       *OldKeys               `protobuf:"bytes,5,opt,name=old_keys,json=oldKeys,proto3" json:"old_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DMLData) Reset() {
	*x = DMLData{}
	mi := &file_api_change_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DMLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DMLData) ProtoMessage() {}

func (x *DMLData) ProtoReflect() protoreflect.Message {
	mi := &file_api_change_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DMLData.ProtoReflect.Descriptor instead.
func (*DMLData) Descriptor() ([]byte, []int) {
	return file_api_change_stream_proto_rawDescGZIP(), []int{2}
}

func (x *DMLData) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *DMLData) GetColumnNames() []string {
	if x != nil {
		return x.ColumnNames
	}
	return nil
}

func (x *DMLData) GetColumnValues() []string {
	if x != nil {
		return x.ColumnValues
	}
	return nil
}

func (x *DMLData) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DMLData) GetOldKeys() *OldKeys {
	if x != nil {
		return x.OldKeys
	}
	return nil
}

type OldKeys struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyNames      []string               `protobuf:"bytes,1,rep,name=key_names,json=keyNames,proto3" json:"key_names,omitempty"`
	KeyValues     []string               `protobuf:"bytes,2,rep,name=key_values,json=keyValues,proto3" json:"key_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OldKeys) Reset() {
	*x = OldKeys{}
	mi := &file_api_change_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OldKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OldKeys) ProtoMessage() {}

func (x *OldKeys) ProtoReflect() protoreflect.Message {
	mi := &file_api_change_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OldKeys.ProtoReflect.Descriptor instead.
func (*OldKeys) Descriptor() ([]byte, []int) {
	return file_api_change_stream_proto_rawDescGZIP(), []int{3}
}

func (x *OldKeys) GetKeyNames() []string {
	if x != nil {
		return x.KeyNames
	}
	return nil
}

func (x *OldKeys) GetKeyValues() []string {
	if x != nil {
		return x.KeyValues
	}
	return nil
}

type DDLData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Database      string                 `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Ddl           string                 `protobuf:"bytes,5,opt,name=ddl,proto3" json:"ddl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DDLData) Reset() {
	*x = DDLData{}
	mi := &file_api_change_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DDLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDLData) ProtoMessage() {}

func (x *DDLData) ProtoReflect() protoreflect.Message {
	mi := &file_api_change_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDLData.ProtoReflect.Descriptor instead.
func (*DDLData) Descriptor() ([]byte, []int) {
	return file_api_change_stream_proto_rawDescGZIP(), []int{4}
}

func (x *DDLData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DDLData) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *DDLData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DDLData) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DDLData) GetDdl() string {
	if x != nil {
		return x.Ddl
	}
	return ""
}

var File_api_change_stream_proto protoreflect.FileDescriptor

const file_api_change_stream_proto_rawDesc = "" +
	"\n" +
	"\x17api/change_stream.proto\x12\rchange_stream\"*\n" +
	"\rStreamRequest\x12\x19\n" +
	"\blast_lsn\x18\x01 \x01(\tR\alastLsn\"\x8e\x01\n" +
	"\x06Change\x12\x10\n" +
	"\x03lsn\x18\x01 \x01(\tR\x03lsn\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12*\n" +
	"\x03dml\x18\x03 \x01(\v2\x16.change_stream.DMLDataH\x00R\x03dml\x12*\n" +
	"\x03ddl\x18\x04 \x01(\v2\x16.change_stream.DDLDataH\x00R\x03ddlB\x06\n" +
	"\x04data\"\xae\x01\n" +
	"\aDMLData\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12!\n" +
	"\fcolumn_names\x18\x02 \x03(\tR\vcolumnNames\x12#\n" +
	"\rcolumn_values\x18\x03 \x03(\tR\fcolumnValues\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x121\n" +
	"\bold_keys\x18\x05 \x01(\v2\x16.change_stream.OldKeysR\aoldKeys\"E\n" +
	"\aOldKeys\x12\x1b\n" +
	"\tkey_names\x18\x01 \x03(\tR\bkeyNames\x12\x1d\n" +
	"\n" +
	"key_values\x18\x02 \x03(\tR\tkeyValues\"w\n" +
	"\aDDLData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bdatabase\x18\x04 \x01(\tR\bdatabase\x12\x10\n" +
	"\x03ddl\x18\x05 \x01(\tR\x03ddl2Q\n" +
	"\fChangeStream\x12A\n" +
	"\x06Stream\x12\x1c.change_stream.StreamRequest\x1a\x15.change_stream.Change\"\x000\x01B?Z=github.com/jeffreywescott/kasho/services/pg-change-stream/apib\x06proto3"

var (
	file_api_change_stream_proto_rawDescOnce sync.Once
	file_api_change_stream_proto_rawDescData []byte
)

func file_api_change_stream_proto_rawDescGZIP() []byte {
	file_api_change_stream_proto_rawDescOnce.Do(func() {
		file_api_change_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_change_stream_proto_rawDesc), len(file_api_change_stream_proto_rawDesc)))
	})
	return file_api_change_stream_proto_rawDescData
}

var file_api_change_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_change_stream_proto_goTypes = []any{
	(*StreamRequest)(nil), // 0: change_stream.StreamRequest
	(*Change)(nil),        // 1: change_stream.Change
	(*DMLData)(nil),       // 2: change_stream.DMLData
	(*OldKeys)(nil),       // 3: change_stream.OldKeys
	(*DDLData)(nil),       // 4: change_stream.DDLData
}
var file_api_change_stream_proto_depIdxs = []int32{
	2, // 0: change_stream.Change.dml:type_name -> change_stream.DMLData
	4, // 1: change_stream.Change.ddl:type_name -> change_stream.DDLData
	3, // 2: change_stream.DMLData.old_keys:type_name -> change_stream.OldKeys
	0, // 3: change_stream.ChangeStream.Stream:input_type -> change_stream.StreamRequest
	1, // 4: change_stream.ChangeStream.Stream:output_type -> change_stream.Change
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_change_stream_proto_init() }
func file_api_change_stream_proto_init() {
	if File_api_change_stream_proto != nil {
		return
	}
	file_api_change_stream_proto_msgTypes[1].OneofWrappers = []any{
		(*Change_Dml)(nil),
		(*Change_Ddl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_change_stream_proto_rawDesc), len(file_api_change_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_change_stream_proto_goTypes,
		DependencyIndexes: file_api_change_stream_proto_depIdxs,
		MessageInfos:      file_api_change_stream_proto_msgTypes,
	}.Build()
	File_api_change_stream_proto = out.File
	file_api_change_stream_proto_goTypes = nil
	file_api_change_stream_proto_depIdxs = nil
}
