version: '3'

vars:
  SERVICES:
    sh: find services -maxdepth 2 -name go.mod -exec dirname {} \; | sort
  TOOLS:
    sh: find tools -maxdepth 2 -name go.mod -exec dirname {} \; | sort
  PACKAGES:
    sh: find pkg -maxdepth 2 -name go.mod -exec dirname {} \; | sort
  APPS:
    sh: find apps -maxdepth 2 -name package.json -exec dirname {} \; | grep -v node_modules | sort

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  build:
    desc: Build the kasho Docker image for development
    cmds:
      - docker build -t kasho --target development .

  proto:
    desc: Generate Go code from protobuf definitions
    cmds:
      - protoc --go_out=proto/kasho --go_opt=paths=source_relative --go-grpc_out=proto/kasho --go-grpc_opt=paths=source_relative proto/change_stream.proto

  test:
    desc: Run all tests (Go services + Next.js apps)
    deps: [test:go, test:apps]
    cmds:
      - echo "✅ All tests passed!"

  test:go:
    desc: Run tests for all Go services and packages
    cmds:
      - |
        dirs="{{.SERVICES}} {{.TOOLS}} {{.PACKAGES}} proto/kasho/proto"
        for dir in $dirs; do
          echo "🧪 Testing $(basename $dir)..."
          if [ -n "$(find "$dir" -name '*_test.go' -print -quit)" ]; then
            (cd "$dir" && go test -v -race -coverprofile=coverage.out ./... && go tool cover -func=coverage.out)
          else
            echo "  ⏭️  No test files found, skipping..."
          fi
        done

  test:apps:
    desc: Run tests for all Next.js apps
    cmds:
      - |
        dirs="{{.APPS}}"
        for dir in $dirs; do
          echo "🧪 Testing $(basename $dir) app..."
          (cd "$dir" && npm run test)
        done

  # Individual component testing (for convenience)
  test:service:*:
    desc: Run tests for a specific service
    cmds:
      - echo "🧪 Testing {{index .MATCH 0}} service..."
      - |
        cd services/{{index .MATCH 0}}
        if [ -n "$(find . -name '*_test.go' -print -quit)" ]; then
          go test -v -race -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
        else
          echo "  ⏭️  No test files found"
        fi

  test:tool:*:
    desc: Run tests for a specific tool
    cmds:
      - echo "🧪 Testing {{index .MATCH 0}} tool..."
      - |
        cd tools/{{index .MATCH 0}}
        if [ -n "$(find . -name '*_test.go' -print -quit)" ]; then
          go test -v -race -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
        else
          echo "  ⏭️  No test files found"
        fi

  test:pkg:*:
    desc: Run tests for a specific package
    cmds:
      - echo "🧪 Testing {{index .MATCH 0}} package..."
      - |
        cd pkg/{{index .MATCH 0}}
        if [ -n "$(find . -name '*_test.go' -print -quit)" ]; then
          go test -v -race -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
        else
          echo "  ⏭️  No test files found"
        fi

  test:app:*:
    desc: Run tests for a specific app
    cmds:
      - echo "🧪 Testing {{index .MATCH 0}} app..."
      - cd apps/{{index .MATCH 0}} && npm run test

  dev:
    desc: Start development environment (alias for dev:start)
    deps: [dev:start]

  dev:start:
    desc: Start development environment
    deps: [build]
    cmds:
      - cd environments/development && docker-compose up

  dev:stop:
    desc: Stop development environment and remove volumes
    cmds:
      - cd environments/development && docker-compose down -v

  dev:reset:
    desc: Reset and restart development environment (removes volumes)
    deps: [dev:stop, dev:start]

  dev:setup-replication:
    desc: Setup replication for the development environment
    cmds:
      - ./scripts/setup-replication.sh

  dev:setup-data:
    desc: Setup fake SaaS data for the development environment
    cmds:
      - ./scripts/demo-fake-projmgmt-saas.sh

  dev:app:*:
    desc: Start a specific app in development mode
    cmds:
      - cd apps/{{index .MATCH 0}} && npm run dev

  # Lint tasks
  lint:
    desc: Run linting for all code
    cmds:
      - task: lint:go
      - task: lint:apps

  lint:go:
    desc: Run linting for Go services and packages
    cmds:
      - |
        dirs="{{.SERVICES}} {{.TOOLS}} {{.PACKAGES}} proto/kasho/proto"
        for dir in $dirs; do
          echo "🔍 Linting $(basename $dir)..."
          (cd "$dir" && go vet ./...)
        done

  lint:apps:
    desc: Run linting for Next.js apps
    cmds:
      - |
        dirs="{{.APPS}}"
        for dir in $dirs; do
          echo "🔍 Linting $(basename $dir) app..."
          (cd "$dir" && npm run lint)
        done

  lint:app:*:
    desc: Lint a specific app
    cmds:
      - echo "🔍 Linting {{index .MATCH 0}} app..."
      - cd apps/{{index .MATCH 0}} && npm run lint

