version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  dev:
    desc: Start development environment
    cmds:
      - cd environments/development && docker-compose up --build

  dev-down:
    desc: Stop development environment
    cmds:
      - cd environments/development && docker-compose down

  dev-reset:
    desc: Reset and restart development environment (removes volumes)
    cmds:
      - cd environments/development && docker-compose down -v && docker-compose up --build

  test:
    desc: Run tests for all services
    deps: [proto]
    cmds:
      - cd services/pg-change-stream && go test ./... 
      - cd services/pg-translicator && go test ./...

  proto:
    desc: Generate Go code from protobuf definitions
    cmds:
      - cd services/pg-change-stream && protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative api/change_stream.proto

  gen-fake-saas-data:
    desc: Generate fake SaaSdata for the demo environment
    cmds:
      - go run tools/generate-fake-saas-data/main.go > environments/demo/sql/fake_projmgmt_saas.sql
