version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  proto:
    desc: Generate Go code from protobuf definitions
    cmds:
      - protoc --go_out=proto/kasho --go_opt=paths=source_relative --go-grpc_out=proto/kasho --go-grpc_opt=paths=source_relative proto/change_stream.proto

  test:
    desc: Run tests for all services
    deps: [proto]
    cmds:
      - cd services/pg-change-stream && go test ./... 
      - cd services/pg-translicator && go test ./...

  dev:
    desc: Start development environment
    cmds:
      - cd environments/development && docker-compose up --build

  dev-reset:
    desc: Reset and restart development environment (removes volumes)
    cmds:
      - cd environments/development && docker-compose down -v && docker-compose up --build

  dev-setup-replication:
    desc: Setup replication for the development environment
    cmds:
      - ./scripts/setup-replication.sh

  dev-setup-data:
    desc: Setup fake SaaS data for the development environment
    cmds:
      - ./scripts/demo-fake-projmgmt-saas.sh

  gen-fake-saas-data:
    desc: Generate fake SaaSdata for the demo environment
    cmds:
      - go run tools/generate-fake-saas-data/main.go > environments/demo/sql/fake_projmgmt_saas.sql

  app-demo:
    desc: Start the demo app
    cmds:
      - cd apps/demo && npm run dev

  app-homepage:
    desc: Start the homepage app
    cmds:
      - cd apps/homepage && npm run dev

  gen-sql-init-files:
    desc: Substitute environment variables in SQL templates for a given environment
    cmds:
      - |
        export $(cat environments/{{.ENV}}/.env | xargs) && \
        tools/env-template/env-template --dirs "environments/{{.ENV}}/primary-init.d,environments/{{.ENV}}/replica-init.d"
    vars:
      ENV:
        sh: 'echo ${ENV:-development}'
    required_vars: [ENV]