// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/change_stream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChangeStream_Stream_FullMethodName = "/change_stream.ChangeStream/Stream"
)

// ChangeStreamClient is the client API for ChangeStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChangeStreamClient interface {
	// Stream returns a stream of changes after the given LSN
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Change], error)
}

type changeStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewChangeStreamClient(cc grpc.ClientConnInterface) ChangeStreamClient {
	return &changeStreamClient{cc}
}

func (c *changeStreamClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Change], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeStream_ServiceDesc.Streams[0], ChangeStream_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, Change]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeStream_StreamClient = grpc.ServerStreamingClient[Change]

// ChangeStreamServer is the server API for ChangeStream service.
// All implementations must embed UnimplementedChangeStreamServer
// for forward compatibility.
type ChangeStreamServer interface {
	// Stream returns a stream of changes after the given LSN
	Stream(*StreamRequest, grpc.ServerStreamingServer[Change]) error
	mustEmbedUnimplementedChangeStreamServer()
}

// UnimplementedChangeStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChangeStreamServer struct{}

func (UnimplementedChangeStreamServer) Stream(*StreamRequest, grpc.ServerStreamingServer[Change]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedChangeStreamServer) mustEmbedUnimplementedChangeStreamServer() {}
func (UnimplementedChangeStreamServer) testEmbeddedByValue()                      {}

// UnsafeChangeStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChangeStreamServer will
// result in compilation errors.
type UnsafeChangeStreamServer interface {
	mustEmbedUnimplementedChangeStreamServer()
}

func RegisterChangeStreamServer(s grpc.ServiceRegistrar, srv ChangeStreamServer) {
	// If the following call pancis, it indicates UnimplementedChangeStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChangeStream_ServiceDesc, srv)
}

func _ChangeStream_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeStreamServer).Stream(m, &grpc.GenericServerStream[StreamRequest, Change]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeStream_StreamServer = grpc.ServerStreamingServer[Change]

// ChangeStream_ServiceDesc is the grpc.ServiceDesc for ChangeStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChangeStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "change_stream.ChangeStream",
	HandlerType: (*ChangeStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _ChangeStream_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/change_stream.proto",
}
