// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: proto/change_stream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastPosition  string                 `protobuf:"bytes,1,opt,name=last_position,json=lastPosition,proto3" json:"last_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_change_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_change_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_change_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetLastPosition() string {
	if x != nil {
		return x.LastPosition
	}
	return ""
}

type Change struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Position string                 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Type     string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Change_Dml
	//	*Change_Ddl
	Data          isChange_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_proto_change_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_proto_change_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_proto_change_stream_proto_rawDescGZIP(), []int{1}
}

func (x *Change) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Change) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Change) GetData() isChange_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Change) GetDml() *DMLData {
	if x != nil {
		if x, ok := x.Data.(*Change_Dml); ok {
			return x.Dml
		}
	}
	return nil
}

func (x *Change) GetDdl() *DDLData {
	if x != nil {
		if x, ok := x.Data.(*Change_Ddl); ok {
			return x.Ddl
		}
	}
	return nil
}

type isChange_Data interface {
	isChange_Data()
}

type Change_Dml struct {
	Dml *DMLData `protobuf:"bytes,3,opt,name=dml,proto3,oneof"`
}

type Change_Ddl struct {
	Ddl *DDLData `protobuf:"bytes,4,opt,name=ddl,proto3,oneof"`
}

func (*Change_Dml) isChange_Data() {}

func (*Change_Ddl) isChange_Data() {}

type ColumnValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ColumnValue_StringValue
	//	*ColumnValue_IntValue
	//	*ColumnValue_FloatValue
	//	*ColumnValue_BoolValue
	//	*ColumnValue_TimestampValue
	Value         isColumnValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnValue) Reset() {
	*x = ColumnValue{}
	mi := &file_proto_change_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnValue) ProtoMessage() {}

func (x *ColumnValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_change_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnValue.ProtoReflect.Descriptor instead.
func (*ColumnValue) Descriptor() ([]byte, []int) {
	return file_proto_change_stream_proto_rawDescGZIP(), []int{2}
}

func (x *ColumnValue) GetValue() isColumnValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ColumnValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*ColumnValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *ColumnValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*ColumnValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *ColumnValue) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*ColumnValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *ColumnValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*ColumnValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *ColumnValue) GetTimestampValue() string {
	if x != nil {
		if x, ok := x.Value.(*ColumnValue_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return ""
}

type isColumnValue_Value interface {
	isColumnValue_Value()
}

type ColumnValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ColumnValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type ColumnValue_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,3,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type ColumnValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type ColumnValue_TimestampValue struct {
	TimestampValue string `protobuf:"bytes,5,opt,name=timestamp_value,json=timestampValue,proto3,oneof"` // ISO 8601 format
}

func (*ColumnValue_StringValue) isColumnValue_Value() {}

func (*ColumnValue_IntValue) isColumnValue_Value() {}

func (*ColumnValue_FloatValue) isColumnValue_Value() {}

func (*ColumnValue_BoolValue) isColumnValue_Value() {}

func (*ColumnValue_TimestampValue) isColumnValue_Value() {}

type DMLData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	ColumnNames   []string               `protobuf:"bytes,2,rep,name=column_names,json=columnNames,proto3" json:"column_names,omitempty"`
	ColumnValues  []*ColumnValue         `protobuf:"bytes,3,rep,name=column_values,json=columnValues,proto3" json:"column_values,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	OldKeys       *OldKeys               `protobuf:"bytes,5,opt,name=old_keys,json=oldKeys,proto3" json:"old_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DMLData) Reset() {
	*x = DMLData{}
	mi := &file_proto_change_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DMLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DMLData) ProtoMessage() {}

func (x *DMLData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_change_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DMLData.ProtoReflect.Descriptor instead.
func (*DMLData) Descriptor() ([]byte, []int) {
	return file_proto_change_stream_proto_rawDescGZIP(), []int{3}
}

func (x *DMLData) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *DMLData) GetColumnNames() []string {
	if x != nil {
		return x.ColumnNames
	}
	return nil
}

func (x *DMLData) GetColumnValues() []*ColumnValue {
	if x != nil {
		return x.ColumnValues
	}
	return nil
}

func (x *DMLData) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DMLData) GetOldKeys() *OldKeys {
	if x != nil {
		return x.OldKeys
	}
	return nil
}

type OldKeys struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyNames      []string               `protobuf:"bytes,1,rep,name=key_names,json=keyNames,proto3" json:"key_names,omitempty"`
	KeyValues     []*ColumnValue         `protobuf:"bytes,2,rep,name=key_values,json=keyValues,proto3" json:"key_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OldKeys) Reset() {
	*x = OldKeys{}
	mi := &file_proto_change_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OldKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OldKeys) ProtoMessage() {}

func (x *OldKeys) ProtoReflect() protoreflect.Message {
	mi := &file_proto_change_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OldKeys.ProtoReflect.Descriptor instead.
func (*OldKeys) Descriptor() ([]byte, []int) {
	return file_proto_change_stream_proto_rawDescGZIP(), []int{4}
}

func (x *OldKeys) GetKeyNames() []string {
	if x != nil {
		return x.KeyNames
	}
	return nil
}

func (x *OldKeys) GetKeyValues() []*ColumnValue {
	if x != nil {
		return x.KeyValues
	}
	return nil
}

type DDLData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Database      string                 `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Ddl           string                 `protobuf:"bytes,5,opt,name=ddl,proto3" json:"ddl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DDLData) Reset() {
	*x = DDLData{}
	mi := &file_proto_change_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DDLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDLData) ProtoMessage() {}

func (x *DDLData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_change_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDLData.ProtoReflect.Descriptor instead.
func (*DDLData) Descriptor() ([]byte, []int) {
	return file_proto_change_stream_proto_rawDescGZIP(), []int{5}
}

func (x *DDLData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DDLData) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *DDLData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DDLData) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DDLData) GetDdl() string {
	if x != nil {
		return x.Ddl
	}
	return ""
}

// Bootstrap coordination messages
type StartBootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartPosition string                 `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	SnapshotName  string                 `protobuf:"bytes,2,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBootstrapRequest) Reset() {
	*x = StartBootstrapRequest{}
	mi := &file_proto_change_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBootstrapRequest) ProtoMessage() {}

func (x *StartBootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_change_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBootstrapRequest.ProtoReflect.Descriptor instead.
func (*StartBootstrapRequest) Descriptor() ([]byte, []int) {
	return file_proto_change_stream_proto_rawDescGZIP(), []int{6}
}

func (x *StartBootstrapRequest) GetStartPosition() string {
	if x != nil {
		return x.StartPosition
	}
	return ""
}

func (x *StartBootstrapRequest) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

type CompleteBootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteBootstrapRequest) Reset() {
	*x = CompleteBootstrapRequest{}
	mi := &file_proto_change_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteBootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteBootstrapRequest) ProtoMessage() {}

func (x *CompleteBootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_change_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteBootstrapRequest.ProtoReflect.Descriptor instead.
func (*CompleteBootstrapRequest) Descriptor() ([]byte, []int) {
	return file_proto_change_stream_proto_rawDescGZIP(), []int{7}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_change_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_change_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_change_stream_proto_rawDescGZIP(), []int{8}
}

type BootstrapResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PreviousState      string                 `protobuf:"bytes,2,opt,name=previous_state,json=previousState,proto3" json:"previous_state,omitempty"`
	CurrentState       string                 `protobuf:"bytes,3,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	AccumulatedChanges int64                  `protobuf:"varint,4,opt,name=accumulated_changes,json=accumulatedChanges,proto3" json:"accumulated_changes,omitempty"`
	ReadyToStream      bool                   `protobuf:"varint,5,opt,name=ready_to_stream,json=readyToStream,proto3" json:"ready_to_stream,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BootstrapResponse) Reset() {
	*x = BootstrapResponse{}
	mi := &file_proto_change_stream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapResponse) ProtoMessage() {}

func (x *BootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_change_stream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapResponse.ProtoReflect.Descriptor instead.
func (*BootstrapResponse) Descriptor() ([]byte, []int) {
	return file_proto_change_stream_proto_rawDescGZIP(), []int{9}
}

func (x *BootstrapResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BootstrapResponse) GetPreviousState() string {
	if x != nil {
		return x.PreviousState
	}
	return ""
}

func (x *BootstrapResponse) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

func (x *BootstrapResponse) GetAccumulatedChanges() int64 {
	if x != nil {
		return x.AccumulatedChanges
	}
	return 0
}

func (x *BootstrapResponse) GetReadyToStream() bool {
	if x != nil {
		return x.ReadyToStream
	}
	return false
}

type StatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	State              string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	StartPosition      string                 `protobuf:"bytes,2,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	CurrentPosition    string                 `protobuf:"bytes,3,opt,name=current_position,json=currentPosition,proto3" json:"current_position,omitempty"`
	AccumulatedChanges int64                  `protobuf:"varint,4,opt,name=accumulated_changes,json=accumulatedChanges,proto3" json:"accumulated_changes,omitempty"`
	ConnectedClients   int32                  `protobuf:"varint,5,opt,name=connected_clients,json=connectedClients,proto3" json:"connected_clients,omitempty"`
	UptimeSeconds      int64                  `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_change_stream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_change_stream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_change_stream_proto_rawDescGZIP(), []int{10}
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusResponse) GetStartPosition() string {
	if x != nil {
		return x.StartPosition
	}
	return ""
}

func (x *StatusResponse) GetCurrentPosition() string {
	if x != nil {
		return x.CurrentPosition
	}
	return ""
}

func (x *StatusResponse) GetAccumulatedChanges() int64 {
	if x != nil {
		return x.AccumulatedChanges
	}
	return 0
}

func (x *StatusResponse) GetConnectedClients() int32 {
	if x != nil {
		return x.ConnectedClients
	}
	return 0
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_proto_change_stream_proto protoreflect.FileDescriptor

const file_proto_change_stream_proto_rawDesc = "" +
	"\n" +
	"\x19proto/change_stream.proto\x12\rchange_stream\"4\n" +
	"\rStreamRequest\x12#\n" +
	"\rlast_position\x18\x01 \x01(\tR\flastPosition\"\x98\x01\n" +
	"\x06Change\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\tR\bposition\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12*\n" +
	"\x03dml\x18\x03 \x01(\v2\x16.change_stream.DMLDataH\x00R\x03dml\x12*\n" +
	"\x03ddl\x18\x04 \x01(\v2\x16.change_stream.DDLDataH\x00R\x03ddlB\x06\n" +
	"\x04data\"\xc9\x01\n" +
	"\vColumnValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x03 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12)\n" +
	"\x0ftimestamp_value\x18\x05 \x01(\tH\x00R\x0etimestampValueB\a\n" +
	"\x05value\"\xca\x01\n" +
	"\aDMLData\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12!\n" +
	"\fcolumn_names\x18\x02 \x03(\tR\vcolumnNames\x12?\n" +
	"\rcolumn_values\x18\x03 \x03(\v2\x1a.change_stream.ColumnValueR\fcolumnValues\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x121\n" +
	"\bold_keys\x18\x05 \x01(\v2\x16.change_stream.OldKeysR\aoldKeys\"a\n" +
	"\aOldKeys\x12\x1b\n" +
	"\tkey_names\x18\x01 \x03(\tR\bkeyNames\x129\n" +
	"\n" +
	"key_values\x18\x02 \x03(\v2\x1a.change_stream.ColumnValueR\tkeyValues\"w\n" +
	"\aDDLData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bdatabase\x18\x04 \x01(\tR\bdatabase\x12\x10\n" +
	"\x03ddl\x18\x05 \x01(\tR\x03ddl\"c\n" +
	"\x15StartBootstrapRequest\x12%\n" +
	"\x0estart_position\x18\x01 \x01(\tR\rstartPosition\x12#\n" +
	"\rsnapshot_name\x18\x02 \x01(\tR\fsnapshotName\"\x1a\n" +
	"\x18CompleteBootstrapRequest\"\x12\n" +
	"\x10GetStatusRequest\"\xd0\x01\n" +
	"\x11BootstrapResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0eprevious_state\x18\x02 \x01(\tR\rpreviousState\x12#\n" +
	"\rcurrent_state\x18\x03 \x01(\tR\fcurrentState\x12/\n" +
	"\x13accumulated_changes\x18\x04 \x01(\x03R\x12accumulatedChanges\x12&\n" +
	"\x0fready_to_stream\x18\x05 \x01(\bR\rreadyToStream\"\xfd\x01\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12%\n" +
	"\x0estart_position\x18\x02 \x01(\tR\rstartPosition\x12)\n" +
	"\x10current_position\x18\x03 \x01(\tR\x0fcurrentPosition\x12/\n" +
	"\x13accumulated_changes\x18\x04 \x01(\x03R\x12accumulatedChanges\x12+\n" +
	"\x11connected_clients\x18\x05 \x01(\x05R\x10connectedClients\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x03R\ruptimeSeconds2\xde\x02\n" +
	"\fChangeStream\x12A\n" +
	"\x06Stream\x12\x1c.change_stream.StreamRequest\x1a\x15.change_stream.Change\"\x000\x01\x12Z\n" +
	"\x0eStartBootstrap\x12$.change_stream.StartBootstrapRequest\x1a .change_stream.BootstrapResponse\"\x00\x12`\n" +
	"\x11CompleteBootstrap\x12'.change_stream.CompleteBootstrapRequest\x1a .change_stream.BootstrapResponse\"\x00\x12M\n" +
	"\tGetStatus\x12\x1f.change_stream.GetStatusRequest\x1a\x1d.change_stream.StatusResponse\"\x00B\x13Z\x11kasho/proto;protob\x06proto3"

var (
	file_proto_change_stream_proto_rawDescOnce sync.Once
	file_proto_change_stream_proto_rawDescData []byte
)

func file_proto_change_stream_proto_rawDescGZIP() []byte {
	file_proto_change_stream_proto_rawDescOnce.Do(func() {
		file_proto_change_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_change_stream_proto_rawDesc), len(file_proto_change_stream_proto_rawDesc)))
	})
	return file_proto_change_stream_proto_rawDescData
}

var file_proto_change_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_change_stream_proto_goTypes = []any{
	(*StreamRequest)(nil),            // 0: change_stream.StreamRequest
	(*Change)(nil),                   // 1: change_stream.Change
	(*ColumnValue)(nil),              // 2: change_stream.ColumnValue
	(*DMLData)(nil),                  // 3: change_stream.DMLData
	(*OldKeys)(nil),                  // 4: change_stream.OldKeys
	(*DDLData)(nil),                  // 5: change_stream.DDLData
	(*StartBootstrapRequest)(nil),    // 6: change_stream.StartBootstrapRequest
	(*CompleteBootstrapRequest)(nil), // 7: change_stream.CompleteBootstrapRequest
	(*GetStatusRequest)(nil),         // 8: change_stream.GetStatusRequest
	(*BootstrapResponse)(nil),        // 9: change_stream.BootstrapResponse
	(*StatusResponse)(nil),           // 10: change_stream.StatusResponse
}
var file_proto_change_stream_proto_depIdxs = []int32{
	3,  // 0: change_stream.Change.dml:type_name -> change_stream.DMLData
	5,  // 1: change_stream.Change.ddl:type_name -> change_stream.DDLData
	2,  // 2: change_stream.DMLData.column_values:type_name -> change_stream.ColumnValue
	4,  // 3: change_stream.DMLData.old_keys:type_name -> change_stream.OldKeys
	2,  // 4: change_stream.OldKeys.key_values:type_name -> change_stream.ColumnValue
	0,  // 5: change_stream.ChangeStream.Stream:input_type -> change_stream.StreamRequest
	6,  // 6: change_stream.ChangeStream.StartBootstrap:input_type -> change_stream.StartBootstrapRequest
	7,  // 7: change_stream.ChangeStream.CompleteBootstrap:input_type -> change_stream.CompleteBootstrapRequest
	8,  // 8: change_stream.ChangeStream.GetStatus:input_type -> change_stream.GetStatusRequest
	1,  // 9: change_stream.ChangeStream.Stream:output_type -> change_stream.Change
	9,  // 10: change_stream.ChangeStream.StartBootstrap:output_type -> change_stream.BootstrapResponse
	9,  // 11: change_stream.ChangeStream.CompleteBootstrap:output_type -> change_stream.BootstrapResponse
	10, // 12: change_stream.ChangeStream.GetStatus:output_type -> change_stream.StatusResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_change_stream_proto_init() }
func file_proto_change_stream_proto_init() {
	if File_proto_change_stream_proto != nil {
		return
	}
	file_proto_change_stream_proto_msgTypes[1].OneofWrappers = []any{
		(*Change_Dml)(nil),
		(*Change_Ddl)(nil),
	}
	file_proto_change_stream_proto_msgTypes[2].OneofWrappers = []any{
		(*ColumnValue_StringValue)(nil),
		(*ColumnValue_IntValue)(nil),
		(*ColumnValue_FloatValue)(nil),
		(*ColumnValue_BoolValue)(nil),
		(*ColumnValue_TimestampValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_change_stream_proto_rawDesc), len(file_proto_change_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_change_stream_proto_goTypes,
		DependencyIndexes: file_proto_change_stream_proto_depIdxs,
		MessageInfos:      file_proto_change_stream_proto_msgTypes,
	}.Build()
	File_proto_change_stream_proto = out.File
	file_proto_change_stream_proto_goTypes = nil
	file_proto_change_stream_proto_depIdxs = nil
}
