// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/license.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateLicenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateLicenseRequest) Reset() {
	*x = ValidateLicenseRequest{}
	mi := &file_proto_license_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateLicenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateLicenseRequest) ProtoMessage() {}

func (x *ValidateLicenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_license_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateLicenseRequest.ProtoReflect.Descriptor instead.
func (*ValidateLicenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_license_proto_rawDescGZIP(), []int{0}
}

type ValidateLicenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                         // empty if valid, error message if invalid
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateLicenseResponse) Reset() {
	*x = ValidateLicenseResponse{}
	mi := &file_proto_license_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateLicenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateLicenseResponse) ProtoMessage() {}

func (x *ValidateLicenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_license_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateLicenseResponse.ProtoReflect.Descriptor instead.
func (*ValidateLicenseResponse) Descriptor() ([]byte, []int) {
	return file_proto_license_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateLicenseResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateLicenseResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ValidateLicenseResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type GetLicenseInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLicenseInfoRequest) Reset() {
	*x = GetLicenseInfoRequest{}
	mi := &file_proto_license_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLicenseInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLicenseInfoRequest) ProtoMessage() {}

func (x *GetLicenseInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_license_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLicenseInfoRequest.ProtoReflect.Descriptor instead.
func (*GetLicenseInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_license_proto_rawDescGZIP(), []int{2}
}

type GetLicenseInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerName  string                 `protobuf:"bytes,2,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	IssuedAt      int64                  `protobuf:"varint,3,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Valid         bool                   `protobuf:"varint,5,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLicenseInfoResponse) Reset() {
	*x = GetLicenseInfoResponse{}
	mi := &file_proto_license_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLicenseInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLicenseInfoResponse) ProtoMessage() {}

func (x *GetLicenseInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_license_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLicenseInfoResponse.ProtoReflect.Descriptor instead.
func (*GetLicenseInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_license_proto_rawDescGZIP(), []int{3}
}

func (x *GetLicenseInfoResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetLicenseInfoResponse) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *GetLicenseInfoResponse) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *GetLicenseInfoResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *GetLicenseInfoResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_proto_license_proto protoreflect.FileDescriptor

const file_proto_license_proto_rawDesc = "" +
	"\n" +
	"\x13proto/license.proto\x12\rkasho.license\"\x18\n" +
	"\x16ValidateLicenseRequest\"f\n" +
	"\x17ValidateLicenseResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"\x17\n" +
	"\x15GetLicenseInfoRequest\"\xb0\x01\n" +
	"\x16GetLicenseInfoResponse\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rcustomer_name\x18\x02 \x01(\tR\fcustomerName\x12\x1b\n" +
	"\tissued_at\x18\x03 \x01(\x03R\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\x12\x14\n" +
	"\x05valid\x18\x05 \x01(\bR\x05valid2\xce\x01\n" +
	"\aLicense\x12b\n" +
	"\x0fValidateLicense\x12%.kasho.license.ValidateLicenseRequest\x1a&.kasho.license.ValidateLicenseResponse\"\x00\x12_\n" +
	"\x0eGetLicenseInfo\x12$.kasho.license.GetLicenseInfoRequest\x1a%.kasho.license.GetLicenseInfoResponse\"\x00B\x1fZ\x1dkasho/proto/kasho/proto;protob\x06proto3"

var (
	file_proto_license_proto_rawDescOnce sync.Once
	file_proto_license_proto_rawDescData []byte
)

func file_proto_license_proto_rawDescGZIP() []byte {
	file_proto_license_proto_rawDescOnce.Do(func() {
		file_proto_license_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_license_proto_rawDesc), len(file_proto_license_proto_rawDesc)))
	})
	return file_proto_license_proto_rawDescData
}

var file_proto_license_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_license_proto_goTypes = []any{
	(*ValidateLicenseRequest)(nil),  // 0: kasho.license.ValidateLicenseRequest
	(*ValidateLicenseResponse)(nil), // 1: kasho.license.ValidateLicenseResponse
	(*GetLicenseInfoRequest)(nil),   // 2: kasho.license.GetLicenseInfoRequest
	(*GetLicenseInfoResponse)(nil),  // 3: kasho.license.GetLicenseInfoResponse
}
var file_proto_license_proto_depIdxs = []int32{
	0, // 0: kasho.license.License.ValidateLicense:input_type -> kasho.license.ValidateLicenseRequest
	2, // 1: kasho.license.License.GetLicenseInfo:input_type -> kasho.license.GetLicenseInfoRequest
	1, // 2: kasho.license.License.ValidateLicense:output_type -> kasho.license.ValidateLicenseResponse
	3, // 3: kasho.license.License.GetLicenseInfo:output_type -> kasho.license.GetLicenseInfoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_license_proto_init() }
func file_proto_license_proto_init() {
	if File_proto_license_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_license_proto_rawDesc), len(file_proto_license_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_license_proto_goTypes,
		DependencyIndexes: file_proto_license_proto_depIdxs,
		MessageInfos:      file_proto_license_proto_msgTypes,
	}.Build()
	File_proto_license_proto = out.File
	file_proto_license_proto_goTypes = nil
	file_proto_license_proto_depIdxs = nil
}
