-- Sample PostgreSQL dump for testing
-- This would typically be generated by pg_dump

-- DDL statements
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    title VARCHAR(200) NOT NULL,
    content TEXT,
    published BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Data statements (COPY format)
COPY users (id, name, email, created_at) FROM stdin;
1	John Doe	john@example.com	2024-01-01 10:00:00
2	Jane Smith	jane@example.com	2024-01-01 11:00:00
3	Bob Johnson	bob@example.com	2024-01-01 12:00:00
\.

COPY posts (id, user_id, title, content, published, created_at) FROM stdin;
1	1	First Post	This is the first post content	t	2024-01-01 10:30:00
2	1	Second Post	This is the second post	f	2024-01-01 11:30:00
3	2	Jane's Post	Hello world from Jane	t	2024-01-01 12:30:00
\.